<!DOCTYPE html>

<html lang="es">
<head><meta charset="utf-8"/>
<link href="Styles/Style00.css" rel="stylesheet" type="text/css"/>
<style type="text/css">body{margin:1em;background-color:transparent!important;}#sbo-rt-content *{text-indent:0pt!important;}#sbo-rt-content .bq{margin-right:1em!important;}#sbo-rt-content *{word-wrap:break-word!important;word-break:break-word!important;}#sbo-rt-content table,#sbo-rt-content pre{overflow-x:unset!important;overflow:unset!important;overflow-y:unset!important;white-space:pre-wrap!important;}</style><meta content="width=device-width, initial-scale=1.0" name="viewport"/><style>
    body {
        width: 74%;
        min-height: 84vh;
        font-size: 16px;
        line-height: 1.5;
        margin: 0;
        padding-left: 13%;
        padding-right: 13%;
        padding-top: 3%;
        }
    
    @media screen and (max-width: 768px) {
        body {
            width: 92%;
            padding-left: 4%;
            padding-right: 4%;
            padding-top: 2%;
            font-size: 14px;
        }
    }
    
    @media screen and (max-width: 480px) {
        body {
            width: 96%;
            padding-left: 2%;
            padding-right: 2%;
            padding-top: 1%;
            font-size: 12px;
        }
    }
</style>
</head>
<body>
<h3 id="h2-502703c10-0009">Manejo de la excepción ZeroDivisionError</h3>
<p class="BodyFirst">Veamos un error sencillo que hace que Python lance una excepción. Probablemente sepas que es imposible dividir un número por cero, pero pidámosle a Python que lo haga de todos modos:</p>
<p class="CodeLabel" translate="no"><b>division_calculator.py</b></p>
<pre translate="no"><code translate="no">print(5/0)</code></pre>
<p>Python no puede hacerlo, así que obtenemos un traceback:</p>
<pre translate="no"><code translate="no">Traceback (most recent call last):
  File "division_calculator.py", line 1, in &lt;module&gt;
    print(5/0)
          ~^~
<span aria-label="annotation1" class="CodeAnnotationHang">❶</span> ZeroDivisionError: division by zero</code></pre>
<p>El error notificado en el traceback, <code translate="no">ZeroDivisionError</code>, es un objeto de excepción <span aria-label="annotation1" class="CodeAnnotation">❶.</span> Python crea este tipo de objeto en respuesta a una situación en la que no puede hacer lo que le pedimos. Cuando esto ocurre, Python detiene el programa y nos indica el tipo de excepción que se ha producido. Podemos utilizar esta información para modificar nuestro programa. Le diremos a Python qué hacer cuando se produzca este tipo de excepción; así, si vuelve a ocurrir, estaremos preparados.</p>
<footer>
<style>
        footer {
            text-align: center;
            margin-top: 2em;
            padding-top: 1em;
            padding-bottom: 2em;
            border-top: 1px solid #eaeaea;
        }
        
        footer a {
            color: #0000FF; /* Color azul para los enlaces */
            text-decoration: none; /* Opcional: elimina el subrayado de los enlaces */
            margin-left: 1em;
            margin-right: 1em;
        }
        footer a:hover {
            text-decoration: underline; /* Opcional: subraya el enlace al pasar el mouse */
        }
    </style>
<p><a href="c10_20.html">anterior</a><a href="c10.html">Subtema 21 de 37: (Ver todo)</a><a href="c10_22.html">siguiente</a><br/></p>
<br/><a href="c10_21.docx" target="_blank"></a></footer>
</body>
</html>
